# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiQt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 494)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_Details = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_Details.setObjectName("tabWidget_Details")
        self.tab_input = QtWidgets.QWidget()
        self.tab_input.setObjectName("tab_input")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_input)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_times = QtWidgets.QTableWidget(self.tab_input)
        self.table_times.setObjectName("table_times")
        self.table_times.setColumnCount(4)
        self.table_times.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_times.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_times.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_times.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_times.setHorizontalHeaderItem(3, item)
        self.table_times.horizontalHeader().setCascadingSectionResizes(True)
        self.table_times.horizontalHeader().setDefaultSectionSize(200)
        self.table_times.horizontalHeader().setStretchLastSection(True)
        self.table_times.verticalHeader().setDefaultSectionSize(50)
        self.gridLayout_2.addWidget(self.table_times, 0, 0, 1, 9)
        self.pushButton_addRow = QtWidgets.QPushButton(self.tab_input)
        self.pushButton_addRow.setObjectName("pushButton_addRow")
        self.gridLayout_2.addWidget(self.pushButton_addRow, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 6, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.tab_input)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 2, 8, 1, 1)
        self.pushButton_deleteEntityRow = QtWidgets.QPushButton(self.tab_input)
        self.pushButton_deleteEntityRow.setObjectName("pushButton_deleteEntityRow")
        self.gridLayout_2.addWidget(self.pushButton_deleteEntityRow, 2, 2, 1, 1)
        self.pushButton_rowUp = QtWidgets.QPushButton(self.tab_input)
        self.pushButton_rowUp.setObjectName("pushButton_rowUp")
        self.gridLayout_2.addWidget(self.pushButton_rowUp, 2, 4, 1, 1)
        self.pushButton_rowDown = QtWidgets.QPushButton(self.tab_input)
        self.pushButton_rowDown.setObjectName("pushButton_rowDown")
        self.gridLayout_2.addWidget(self.pushButton_rowDown, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        self.tabWidget_Details.addTab(self.tab_input, "")
        self.tab_details = QtWidgets.QWidget()
        self.tab_details.setObjectName("tab_details")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_details)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_bookings = QtWidgets.QTableWidget(self.tab_details)
        self.table_bookings.setObjectName("table_bookings")
        self.table_bookings.setColumnCount(5)
        self.table_bookings.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_bookings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bookings.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bookings.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bookings.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_bookings.setHorizontalHeaderItem(4, item)
        self.table_bookings.horizontalHeader().setDefaultSectionSize(200)
        self.table_bookings.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.table_bookings, 0, 1, 1, 8)
        self.pushButton_bookingRowUp = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_bookingRowUp.setObjectName("pushButton_bookingRowUp")
        self.gridLayout_3.addWidget(self.pushButton_bookingRowUp, 2, 4, 1, 1)
        self.pushButton_bookingRowDown = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_bookingRowDown.setObjectName("pushButton_bookingRowDown")
        self.gridLayout_3.addWidget(self.pushButton_bookingRowDown, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 6, 1, 1)
        self.pushButton_addBookRow = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_addBookRow.setObjectName("pushButton_addBookRow")
        self.gridLayout_3.addWidget(self.pushButton_addBookRow, 2, 1, 1, 1)
        self.pushButton_saveBookRow = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_saveBookRow.setObjectName("pushButton_saveBookRow")
        self.gridLayout_3.addWidget(self.pushButton_saveBookRow, 2, 8, 1, 1)
        self.pushButton_deleteBookingRow = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_deleteBookingRow.setObjectName("pushButton_deleteBookingRow")
        self.gridLayout_3.addWidget(self.pushButton_deleteBookingRow, 2, 2, 1, 1)
        self.pushButton_copyTime = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_copyTime.setObjectName("pushButton_copyTime")
        self.gridLayout_3.addWidget(self.pushButton_copyTime, 2, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 3, 1, 1)
        self.label_sumHours = QtWidgets.QLabel(self.tab_details)
        self.label_sumHours.setObjectName("label_sumHours")
        self.gridLayout_3.addWidget(self.label_sumHours, 1, 4, 1, 1)
        self.tabWidget_Details.addTab(self.tab_details, "")
        self.gridLayout.addWidget(self.tabWidget_Details, 0, 1, 1, 1)
        self.list_days = QtWidgets.QListWidget(self.centralWidget)
        self.list_days.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_days.setObjectName("list_days")
        self.gridLayout.addWidget(self.list_days, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1070, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_AddDay = QtWidgets.QAction(MainWindow)
        self.action_AddDay.setObjectName("action_AddDay")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menuMenu.addAction(self.action_AddDay)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.action_Exit)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_Details.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_times.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "from"))
        item = self.table_times.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "to"))
        item = self.table_times.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "order"))
        item = self.table_times.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "comment"))
        self.pushButton_addRow.setText(_translate("MainWindow", "Add row"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_deleteEntityRow.setText(_translate("MainWindow", "Delete row"))
        self.pushButton_rowUp.setText(_translate("MainWindow", "Up"))
        self.pushButton_rowDown.setText(_translate("MainWindow", "Down"))
        self.tabWidget_Details.setTabText(self.tabWidget_Details.indexOf(self.tab_input), _translate("MainWindow", "Working times"))
        item = self.table_bookings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order"))
        item = self.table_bookings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hours"))
        item = self.table_bookings.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Booked"))
        item = self.table_bookings.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Logged"))
        item = self.table_bookings.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Comment"))
        self.pushButton_bookingRowUp.setText(_translate("MainWindow", "Up"))
        self.pushButton_bookingRowDown.setText(_translate("MainWindow", "Down"))
        self.pushButton_addBookRow.setText(_translate("MainWindow", "Add row"))
        self.pushButton_saveBookRow.setText(_translate("MainWindow", "Save"))
        self.pushButton_deleteBookingRow.setText(_translate("MainWindow", "Delete row"))
        self.pushButton_copyTime.setText(_translate("MainWindow", "Copy times"))
        self.label_sumHours.setText(_translate("MainWindow", "Sum: 0 hrs"))
        self.tabWidget_Details.setTabText(self.tabWidget_Details.indexOf(self.tab_details), _translate("MainWindow", "Bookings"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.action_AddDay.setText(_translate("MainWindow", "Add day"))
        self.action_Exit.setText(_translate("MainWindow", "Exit"))

